apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: php-fpm
          image: sachinxfdo/laravel-app:latest
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: env-file
              mountPath: /var/www/html/.env
              subPath: .env

        - name: nginx
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
          command: ["/bin/sh"]
          args: ["-c", "nginx -g 'daemon off;'"]

      volumes:
        - name: nginx-config
          configMap:
            name: laravel-nginx-config
        - name: env-file
          secret:
            secretName: laravel-env
