apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 9000
          env:
            - name: APP_ENV
              value: production
