apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: php-fpm
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: env-file
              mountPath: /var/www/html/.env
              subPath: .env
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: laravel
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
                  
        - name: nginx
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
          command: ["/bin/sh"]
          args: ["-c", "nginx -g 'daemon off;'"]

      volumes:
        - name: nginx-config
          configMap:
            name: laravel-nginx-config
        - name: env-file
          secret:
            secretName: laravel-env
