apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: MTIzODEy     # base64 for "password123"
  mysql-password: MTIzODEy          # base64 for "password123"
